name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump Google Services configuration
      run: echo "${{ secrets.GOOGLE_SERVICES }}" >> google-services.json

    - name: Check Google Services configuration
      run: cat google-services.json
